import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "libs/dbviewer/**/*.test.ts",
      "libs/unixtime/**/*.test.ts",
      "libs/cron/**/*.test.ts",
      "libs/qrcode/**/*.test.ts",
      "libs/textcase/**/*.test.ts",
      "libs/color/**/*.test.ts",
      "libs/regex/**/*.test.ts",
      "libs/csv/**/*.test.ts",
      "libs/numbase/**/*.test.ts",
      "libs/deduplines/**/*.test.ts",
      "libs/image/**/*.test.ts",
      "libs/image-to-pdf/**/*.test.ts",
      "libs/extractor/**/*.test.ts",
      "libs/password/**/*.test.ts",
      "libs/pdf-merge/**/*.test.ts",
      "libs/wordcounter/**/*.test.ts",
      "libs/token-counter/**/*.test.ts",
      "libs/sshkey/**/*.test.ts",
      "libs/httpclient/**/*.test.ts",
      "libs/wallet/**/*.test.ts",
      "libs/cssunit/**/*.test.ts",
      "libs/jsonts/**/*.test.ts",
      "libs/subnet/**/*.test.ts",
      "libs/sqlformat/**/*.test.ts",
      "libs/recipe/**/*.test.ts",
      "libs/batch/**/*.test.ts",
      "libs/__tests__/*.test.ts",
      "utils/__tests__/*.test.{ts,tsx}",
      "hooks/**/*.test.ts",
    ],
    environment: "node",
    pool: "forks",
    globals: false,
  },
});
