export interface CharacterData {
    entityName?: string;
    entityNumber: number;
    description: string;
}
export interface PronunciationCharacterData {
    entityName?: string;
    ipaEntityName?: string;
    code: string;
    ipaCode?: string;
    example: string;
}
export function getPronunciations(): PronunciationCharacterData[] {
    return [
        { entityName: '', 'ipaEntityName': '&aelig;', 'code': '&#259; ', 'ipaCode': '&#230;', example: 'c<span class="text-success fw-bold">a</span>t' },
        { entityName: '', 'ipaEntityName': 'e', 'code': '&#257; ', 'ipaCode': 'e', example: 'd<span class="text-success fw-bold">ay</span>' },
        { entityName: '&acirc;', 'ipaEntityName': '', 'code': '&#226; ', 'ipaCode': '', example: 'b<span class="text-success fw-bold">ea</span>r' },
        { entityName: '&auml;', 'ipaEntityName': 'a', 'code': '&#228; ', 'ipaCode': 'a', example: 'f<span class="text-success fw-bold">a</span>ther' },
        { entityName: 'b', 'ipaEntityName': 'b', 'code': 'b ', 'ipaCode': 'b', example: '<span class="text-success fw-bold">b</span>oy' },
        { entityName: 'ch', 'ipaEntityName': '&ccedil;', 'code': 'ch ', 'ipaCode': '&#231;', example: '<span class="text-success fw-bold">ch</span>air' },
        { entityName: 'd', 'ipaEntityName': 'd', 'code': 'd ', 'ipaCode': 'd', example: '<span class="text-success fw-bold">d</span>ay or play<span class="text-success fw-bold">ed</span>' },
        { entityName: '', 'ipaEntityName': '&epsilon;', 'code': '&#277; ', 'ipaCode': '&#949;', example: 'p<span class="text-success fw-bold">e</span>t' },
        { entityName: '', 'ipaEntityName': 'i', 'code': '&#275; ', 'ipaCode': 'i', example: 's<span class="text-success fw-bold">ee</span>' },
        { entityName: '', 'ipaEntityName': '&phi;', 'code': 'f ', 'ipaCode': '&#966;', example: '<span class="text-success fw-bold">f</span>ine or <span class="text-success fw-bold">ph</span>oto or tou<span class="text-success fw-bold">gh</span>' },
        { entityName: 'g', 'ipaEntityName': 'g', 'code': 'g ', 'ipaCode': 'g', example: '<span class="text-success fw-bold">g</span>ive' },
        { entityName: 'h', 'ipaEntityName': 'h', 'code': 'h ', 'ipaCode': 'h', example: '<span class="text-success fw-bold">h</span>at' },
        { entityName: '', 'ipaEntityName': 'I', 'code': '&#301; ', 'ipaCode': 'I', example: 'p<span class="text-success fw-bold">i</span>t' },
        { entityName: '', 'ipaEntityName': 'ai', 'code': '&#299; ', 'ipaCode': 'ai', example: 'd<span class="text-success fw-bold">ie</span> or m<span class="text-success fw-bold">y</span>' },
        { entityName: '&icirc;', 'ipaEntityName': '', 'code': '&#238; ', 'ipaCode': '', example: '<span class="text-success fw-bold">ear</span>' },
        { entityName: 'j', 'ipaEntityName': 'j', 'code': 'j ', 'ipaCode': 'j', example: '<span class="text-success fw-bold">j</span>enn or <span class="text-success fw-bold">g</span>entle' },
        { entityName: 'k', 'ipaEntityName': 'k', 'code': 'k ', 'ipaCode': 'k', example: '<span class="text-success fw-bold">c</span>at or <span class="text-success fw-bold">k</span>i<span class="text-success fw-bold">ck</span> or pi<span class="text-success fw-bold">qu</span>e' },
        { entityName: 'l', 'ipaEntityName': 'l', 'code': 'l ', 'ipaCode': 'l', example: '<span class="text-success fw-bold">l</span>it or gent<span class="text-success fw-bold">le</span>' },
        { entityName: 'm', 'ipaEntityName': 'm', 'code': 'm ', 'ipaCode': 'm', example: '<span class="text-success fw-bold">m</span>at' },
        { entityName: 'n', 'ipaEntityName': 'n', 'code': 'n ', 'ipaCode': 'n', example: '<span class="text-success fw-bold">n</span>o or <span class="text-success fw-bold">kn</span>it or sudd<span class="text-success fw-bold">en</span>' },
        { entityName: 'ng', 'ipaEntityName': '', 'code': 'ng ', 'ipaCode': '&#331;', example: 'si<span class="text-success fw-bold">ng</span>' },
        { entityName: '', 'ipaEntityName': '', 'code': '&#335; ', 'ipaCode': '&#596;', example: 'p<span class="text-success fw-bold">o</span>t' },
        { entityName: '', 'ipaEntityName': 'o', 'code': '&#333; ', 'ipaCode': 'o', example: 't<span class="text-success fw-bold">o</span>w' },
        { entityName: 'ô', 'ipaEntityName': '', 'code': '&#244; ', 'ipaCode': '&#594;', example: 'p<span class="text-success fw-bold">aw</span>' },
        { entityName: '', 'ipaEntityName': '', 'code': '&#335; ', 'ipaCode': '&#611;', example: 'b<span class="text-success fw-bold">oo</span>k' },
        { entityName: '', 'ipaEntityName': 'u', 'code': '&#333; ', 'ipaCode': 'u', example: 'b<span class="text-success fw-bold">oo</span>t' },
        { entityName: 'ou', 'ipaEntityName': 'au', 'code': 'ou ', 'ipaCode': 'au', example: '<span class="text-success fw-bold">ou</span>t' },
        { entityName: 'p', 'ipaEntityName': 'p', 'code': 'p ', 'ipaCode': 'p', example: '<span class="text-success fw-bold">p</span>et' },
        { entityName: 'r', 'ipaEntityName': 'r', 'code': 'r ', 'ipaCode': 'r', example: '<span class="text-success fw-bold">r</span>ed' },
        { entityName: 's', 'ipaEntityName': 's', 'code': 's ', 'ipaCode': 's', example: '<span class="text-success fw-bold">s</span>ay or fen<span class="text-success fw-bold">ce</span>' },
        { entityName: '', 'ipaEntityName': '&int;', 'code': '&#353; ', 'ipaCode': '&#8747;', example: '<span class="text-success fw-bold">sh</span>ed' },
        { entityName: 't', 'ipaEntityName': 't', 'code': 't ', 'ipaCode': 't', example: '<span class="text-success fw-bold">t</span>ip or ripp<span class="text-success fw-bold">ed</span>' },
        { entityName: 'th', 'ipaEntityName': '&theta;', 'code': 'th ', 'ipaCode': '&#952;', example: '<span class="text-success fw-bold">th</span>in' },
        { entityName: 'th(in italics)', 'ipaEntityName': '&thorn;', 'code': 'th', 'ipaCode': '&#254;', example: '<span class="text-success fw-bold">th</span>is' },
        { entityName: '', 'ipaEntityName': '', 'code': '&#365; ', 'ipaCode': '&#592;', example: 'c<span class="text-success fw-bold">u</span>t' },
        { entityName: '&ucirc;r', 'ipaEntityName': '', 'code': '&#251r ', 'ipaCode': '', example: '<span class="text-success fw-bold">ur</span>ge or <span class="text-success fw-bold">er</span>tm or f<span class="text-success fw-bold">ir</span>m' },
        { entityName: 'v', 'ipaEntityName': 'v', 'code': 'v ', 'ipaCode': 'v', example: '<span class="text-success fw-bold">v</span>at' },
        { entityName: 'w', 'ipaEntityName': 'w', 'code': 'w ', 'ipaCode': 'w', example: '<span class="text-success fw-bold">w</span>ith' },
        { entityName: 'y', 'ipaEntityName': 'y', 'code': 'y ', 'ipaCode': 'y', example: '<span class="text-success fw-bold"y></span>es' },
        { entityName: 'zh', 'ipaEntityName': '', 'code': 'zh ', 'ipaCode': '&#658;', example: 'vi<span class="text-success fw-bold">s</span>ion or plea<span class="text-success fw-bold">s</span>ure' },
        { entityName: 'z', 'ipaEntityName': 'z', 'code': 'z ', 'ipaCode': 'z', example: '<span class="text-success fw-bold">z</span>ebra or <span class="text-success fw-bold">x</span>ylophone' },
        { entityName: '', 'ipaEntityName': '', 'code': '&#601; ', 'ipaCode': '&#601;', example: '<span class="text-success fw-bold">a</span>gain or vis<span class="text-success fw-bold">ion</span>' },
        { entityName: '', 'ipaEntityName': '', 'code': '&#602; ', 'ipaCode': '&#602;', example: 'bett<span class="text-success fw-bold">er</span>' },
        { entityName: '&acute;', 'ipaEntityName': '', 'code': '&#180; ', 'ipaCode': '', example: 'primary accent: glo´ bal' },
        { entityName: '', 'ipaEntityName': '', 'code': '&#733; ', 'ipaCode': '', example: 'secondary accent: glo´ ba lize˝' },
    ]

}

export function getIcons(): CharacterData[] {
    return [
        { entityName: '&spades;', entityNumber: 9824, description: 'Spade card suit' },
        { entityName: '&clubs;', entityNumber: 9827, description: 'Clubs card suit' },
        { entityName: '&diams;', entityNumber: 9830, description: 'Diamonds card suit' },
        { entityName: '&hearts;', entityNumber: 9829, description: 'Hearts card suit' },
        { entityName: '&larr;', entityNumber: 8592, description: 'Left arrow' },
        { entityName: '&rarr;', entityNumber: 8594, description: 'Right arrow' },
        { entityName: '&uarr;', entityNumber: 8593, description: 'Up arrow' },
        { entityName: '&darr;', entityNumber: 8595, description: 'Down arrow' },
        { entityName: '', entityNumber: 9833, description: 'Quarter Note' },
        { entityName: '', entityNumber: 9834, description: 'Eighth Note' },
        { entityName: '', entityNumber: 9836, description: 'Two Eighth Notes' },
        { entityName: '', entityNumber: 9837, description: 'Flat' },
        { entityName: '', entityNumber: 9839, description: 'Sharp' },
        { entityName: '', entityNumber: 10047, description: 'Black flower' },
        { entityName: '', entityNumber: 9800, description: '' },
        { entityName: '', entityNumber: 9799, description: '' },
        { entityName: '', entityNumber: 9798, description: '' },
        { entityName: '', entityNumber: 9797, description: '' },
        { entityName: '', entityNumber: 9796, description: '' },
        { entityName: '', entityNumber: 9795, description: '' },
        { entityName: '', entityNumber: 9794, description: 'Male Indicator' },
        { entityName: '', entityNumber: 9793, description: '' },
        { entityName: '', entityNumber: 9792, description: 'Female Indicator' },
        { entityName: '', entityNumber: 9791, description: '' },
        { entityName: '', entityNumber: 9790, description: '' },
        { entityName: '', entityNumber: 9789, description: '' },
        { entityName: '', entityNumber: 9788, description: '' },
        { entityName: '', entityNumber: 9787, description: 'Smiley - Black' },
        { entityName: '', entityNumber: 9786, description: 'Smiley - White' },
        { entityName: '', entityNumber: 9785, description: 'Frowning face' },
        { entityName: '', entityNumber: 9784, description: 'Snow / Cristal' },
        { entityName: '', entityNumber: 9783, description: '' },
        { entityName: '', entityNumber: 9782, description: '' },
        { entityName: '', entityNumber: 9781, description: '' },
        { entityName: '', entityNumber: 9780, description: '' },
        { entityName: '', entityNumber: 9779, description: '' },
        { entityName: '', entityNumber: 9778, description: '' },
        { entityName: '', entityNumber: 9777, description: '' },
        { entityName: '', entityNumber: 9776, description: '' },
        { entityName: '', entityNumber: 9775, description: '' },
        { entityName: '', entityNumber: 9774, description: '' },
        { entityName: '', entityNumber: 9773, description: '' },
        { entityName: '', entityNumber: 9772, description: '' },
        { entityName: '', entityNumber: 9771, description: '' },
        { entityName: '', entityNumber: 9770, description: '' },
        { entityName: '', entityNumber: 9769, description: '' },
        { entityName: '', entityNumber: 9768, description: '' },
        { entityName: '', entityNumber: 9767, description: '' },
        { entityName: '', entityNumber: 9766, description: '' },
        { entityName: '', entityNumber: 9765, description: '' },
        { entityName: '', entityNumber: 9764, description: '' },
        { entityName: '', entityNumber: 9763, description: '' },
        { entityName: '', entityNumber: 9762, description: '' },
        { entityName: '', entityNumber: 9761, description: '' },
        { entityName: '', entityNumber: 9760, description: '' },
        { entityName: '', entityNumber: 9759, description: '' },
        { entityName: '', entityNumber: 9758, description: '' },
        { entityName: '', entityNumber: 9757, description: '' },
        { entityName: '', entityNumber: 9756, description: '' },
        { entityName: '', entityNumber: 9755, description: '' },
        { entityName: '', entityNumber: 9754, description: '' },
        { entityName: '', entityNumber: 9751, description: '' },
        { entityName: '', entityNumber: 9750, description: '' },
        { entityName: '', entityNumber: 9747, description: '' },
        { entityName: '', entityNumber: 9746, description: '' },
        { entityName: '', entityNumber: 9745, description: '' },
        { entityName: '', entityNumber: 9744, description: '' },
        { entityName: '', entityNumber: 9743, description: '' },
        { entityName: '', entityNumber: 9742, description: '' },
        { entityName: '', entityNumber: 9741, description: '' },
        { entityName: '', entityNumber: 9740, description: '' },
        { entityName: '', entityNumber: 9739, description: '' },
        { entityName: '', entityNumber: 9738, description: '' },
        { entityName: '', entityNumber: 9737, description: '' },
        { entityName: '', entityNumber: 9736, description: '' },
        { entityName: '', entityNumber: 9735, description: '' },
        { entityName: '', entityNumber: 9734, description: '' },
        { entityName: '', entityNumber: 9733, description: '' },
        { entityName: '', entityNumber: 9732, description: '' },
        { entityName: '', entityNumber: 9731, description: '' },
        { entityName: '', entityNumber: 9730, description: '' },
        { entityName: '', entityNumber: 9729, description: '' },
        { entityName: '', entityNumber: 9728, description: '' },
        { entityName: '', entityNumber: 9711, description: '' },
        { entityName: '', entityNumber: 9710, description: '' },
        { entityName: '', entityNumber: 9709, description: '' },
        { entityName: '', entityNumber: 9708, description: '' },
        { entityName: '', entityNumber: 9707, description: '' },
        { entityName: '', entityNumber: 9706, description: '' },
        { entityName: '', entityNumber: 9705, description: '' },
        { entityName: '', entityNumber: 9704, description: '' },
        { entityName: '', entityNumber: 9703, description: '' },
        { entityName: '', entityNumber: 9702, description: '' },
        { entityName: '', entityNumber: 9701, description: '' },
        { entityName: '', entityNumber: 9700, description: '' },
        { entityName: '', entityNumber: 9699, description: '' },
        { entityName: '', entityNumber: 9698, description: '' },
        { entityName: '', entityNumber: 9697, description: '' },
        { entityName: '', entityNumber: 9696, description: '' },
        { entityName: '', entityNumber: 9695, description: '' },
        { entityName: '', entityNumber: 9694, description: '' },
        { entityName: '', entityNumber: 9693, description: '' },
        { entityName: '', entityNumber: 9692, description: '' },
        { entityName: '', entityNumber: 9691, description: '' },
        { entityName: '', entityNumber: 9690, description: '' },
        { entityName: '', entityNumber: 9689, description: '' },
    ]
}
export function getAscii(): CharacterData[] {
    return [
        { entityName: '', entityNumber: 9, description: 'Horizontal Tab' },
        { entityName: '', entityNumber: 10, description: 'Line feed' },
        { entityName: '', entityNumber: 32, description: 'space' },
        { entityName: '', entityNumber: 33, description: 'Exclamation point' },
        { entityName: '&quot;', entityNumber: 34, description: 'Double quote' },
        { entityName: '', entityNumber: 35, description: 'Number sign' },
        { entityName: '', entityNumber: 36, description: 'Dollar sign' },
        { entityName: '', entityNumber: 37, description: 'Percent sign' },
        { entityName: '&amp;', entityNumber: 38, description: 'Ampersand (and sign)' },
        { entityName: '', entityNumber: 39, description: 'Single quote' },
        { entityName: '', entityNumber: 40, description: 'Left parenthesis' },
        { entityName: '', entityNumber: 41, description: 'Right parenthesis' },
        { entityName: '', entityNumber: 42, description: 'Asterisk (star)' },
        { entityName: '', entityNumber: 43, description: 'Plus' },
        { entityName: '', entityNumber: 44, description: 'Comma' },
        { entityName: '', entityNumber: 45, description: 'Minus (hyphen)' },
        { entityName: '', entityNumber: 46, description: 'Period' },
        { entityName: '', entityNumber: 47, description: 'Forward slash' },
        { entityName: '', entityNumber: 48, description: 'Zero' },
        { entityName: '', entityNumber: 49, description: 'One' },
        { entityName: '', entityNumber: 50, description: 'Two' },
        { entityName: '', entityNumber: 51, description: 'Three' },
        { entityName: '', entityNumber: 52, description: 'Four' },
        { entityName: '', entityNumber: 53, description: 'Five' },
        { entityName: '', entityNumber: 54, description: 'Six' },
        { entityName: '', entityNumber: 55, description: 'Seven' },
        { entityName: '', entityNumber: 56, description: 'Eight' },
        { entityName: '', entityNumber: 57, description: 'Nine' },
        { entityName: '', entityNumber: 58, description: 'Colon' },
        { entityName: '', entityNumber: 59, description: 'Semi-colon' },
        { entityName: '&lt;', entityNumber: 60, description: 'Less-than sign' },
        { entityName: '', entityNumber: 61, description: 'Equal sign' },
        { entityName: '&gt;', entityNumber: 62, description: 'Greater-than sign' },
        { entityName: '', entityNumber: 63, description: 'Question mark' },
        { entityName: '', entityNumber: 64, description: 'At-sign' },
        { entityName: '', entityNumber: 65, description: 'Capital a' },
        { entityName: '', entityNumber: 66, description: 'Capital b' },
        { entityName: '', entityNumber: 67, description: 'Capital c' },
        { entityName: '', entityNumber: 68, description: 'Capital d' },
        { entityName: '', entityNumber: 69, description: 'Capital e' },
        { entityName: '', entityNumber: 70, description: 'Capital f' },
        { entityName: '', entityNumber: 71, description: 'Capital g' },
        { entityName: '', entityNumber: 72, description: 'Capital h' },
        { entityName: '', entityNumber: 73, description: 'Capital i' },
        { entityName: '', entityNumber: 74, description: 'Capital j' },
        { entityName: '', entityNumber: 75, description: 'Capital k' },
        { entityName: '', entityNumber: 76, description: 'Capital l' },
        { entityName: '', entityNumber: 77, description: 'Capital m' },
        { entityName: '', entityNumber: 78, description: 'Capital n' },
        { entityName: '', entityNumber: 79, description: 'Capital o' },
        { entityName: '', entityNumber: 80, description: 'Capital p' },
        { entityName: '', entityNumber: 81, description: 'Capital q' },
        { entityName: '', entityNumber: 82, description: 'Capital r' },
        { entityName: '', entityNumber: 83, description: 'Capital s' },
        { entityName: '', entityNumber: 84, description: 'Capital t' },
        { entityName: '', entityNumber: 85, description: 'Capital u' },
        { entityName: '', entityNumber: 86, description: 'Capital v' },
        { entityName: '', entityNumber: 87, description: 'Capital w' },
        { entityName: '', entityNumber: 88, description: 'Capital x' },
        { entityName: '', entityNumber: 89, description: 'Capital y' },
        { entityName: '', entityNumber: 90, description: 'Capital z' },
        { entityName: '', entityNumber: 91, description: 'Left square bracket' },
        { entityName: '', entityNumber: 92, description: 'Back slash' },
        { entityName: '', entityNumber: 93, description: 'Right square bracket' },
        { entityName: '', entityNumber: 94, description: 'Caret' },
        { entityName: '', entityNumber: 95, description: 'Underscore' },
        { entityName: '', entityNumber: 96, description: 'Grave accent' },
        { entityName: '', entityNumber: 97, description: 'Lowercase a' },
        { entityName: '', entityNumber: 98, description: 'Lowercase b' },
        { entityName: '', entityNumber: 99, description: 'Lowercase c' },
        { entityName: '', entityNumber: 100, description: 'Lowercase d' },
        { entityName: '', entityNumber: 101, description: 'Lowercase e' },
        { entityName: '', entityNumber: 102, description: 'Lowercase f' },
        { entityName: '', entityNumber: 103, description: 'Lowercase g' },
        { entityName: '', entityNumber: 104, description: 'Lowercase h' },
        { entityName: '', entityNumber: 105, description: 'Lowercase i' },
        { entityName: '', entityNumber: 106, description: 'Lowercase j' },
        { entityName: '', entityNumber: 107, description: 'Lowercase k' },
        { entityName: '', entityNumber: 108, description: 'Lowercase l' },
        { entityName: '', entityNumber: 109, description: 'Lowercase m' },
        { entityName: '', entityNumber: 110, description: 'Lowercase n' },
        { entityName: '', entityNumber: 111, description: 'Lowercase o' },
        { entityName: '', entityNumber: 112, description: 'Lowercase p' },
        { entityName: '', entityNumber: 113, description: 'Lowercase q' },
        { entityName: '', entityNumber: 114, description: 'Lowercase r' },
        { entityName: '', entityNumber: 115, description: 'Lowercase s' },
        { entityName: '', entityNumber: 116, description: 'Lowercase t' },
        { entityName: '', entityNumber: 117, description: 'Lowercase u' },
        { entityName: '', entityNumber: 118, description: 'Lowercase v' },
        { entityName: '', entityNumber: 119, description: 'Lowercase w' },
        { entityName: '', entityNumber: 120, description: 'Lowercase x' },
        { entityName: '', entityNumber: 121, description: 'Lowercase y' },
        { entityName: '', entityNumber: 122, description: 'Lowercase z' },
        { entityName: '', entityNumber: 123, description: 'Left curly brace' },
        { entityName: '', entityNumber: 124, description: 'Vertical bar' },
        { entityName: '', entityNumber: 125, description: 'Right curly brace' },
        { entityName: '&tilde;', entityNumber: 126, description: 'tilde' },
        { entityName: '', entityNumber: 127, description: 'Not defined' },
        { entityName: '', entityNumber: 128, description: 'Euro' },
        { entityName: '', entityNumber: 129, description: 'Unknown' },
        { entityName: '&sbquo;', entityNumber: 130, description: 'Single low-quote' },
        { entityName: '', entityNumber: 131, description: 'Function symbol (lowercase f with hook)' },
        { entityName: '&dbquo;', entityNumber: 132, description: 'Double low-quote' },
        { entityName: '', entityNumber: 133, description: 'Elipsis' },
        { entityName: '&dagger;', entityNumber: 134, description: 'Dagger' },
        { entityName: '&Dagger;', entityNumber: 135, description: 'Double dagger' },
        { entityName: '', entityNumber: 136, description: 'Hatchek' },
        { entityName: '&permil;', entityNumber: 137, description: 'Per million symbol' },
        { entityName: '', entityNumber: 138, description: 'Capital esh' },
        { entityName: '&lsaquo;', entityNumber: 139, description: 'Left single angle quote' },
        { entityName: '', entityNumber: 140, description: 'OE ligature' },
        { entityName: '', entityNumber: 141, description: 'Unknown' },
        { entityName: '', entityNumber: 142, description: 'Capital ž' },
        { entityName: '', entityNumber: 143, description: 'Unknown' },
        { entityName: '', entityNumber: 144, description: 'Unknown' },
        { entityName: '&lsquo;', entityNumber: 145, description: 'Left single-quote' },
        { entityName: '&rsquo;', entityNumber: 146, description: 'Right single-quote' },
        { entityName: '&ldquo;', entityNumber: 147, description: 'Left double-quote' },
        { entityName: '&rdquo;', entityNumber: 148, description: 'Right double-quote' },
        { entityName: '', entityNumber: 149, description: 'Small bullet' },
        { entityName: '&ndash;', entityNumber: 150, description: 'En dash' },
        { entityName: '&mdash;', entityNumber: 151, description: 'Em dash' },
        { entityName: '&tilde', entityNumber: 152, description: 'Tilde' },
        { entityName: '&trade;', entityNumber: 153, description: 'Trademark' },
        { entityName: '', entityNumber: 154, description: 'Lowercase esh' },
        { entityName: '&rsaquo;', entityNumber: 155, description: 'Right single angle quote' },
        { entityName: '', entityNumber: 156, description: 'oe ligature' },
        { entityName: '', entityNumber: 157, description: 'Unknown' },
        { entityName: '', entityNumber: 158, description: 'Lowercase ž' },
        { entityName: '&Yuml;', entityNumber: 159, description: 'Uppercase y-umlaut' },
        { entityName: '&nbsp;', entityNumber: 160, description: 'Non-breaking space' },
        { entityName: '&iexcl;', entityNumber: 161, description: 'Inverted exclamation point' },
        { entityName: '&cent;', entityNumber: 162, description: 'Cent' },
        { entityName: '&pound;', entityNumber: 163, description: 'Pound currency sign' },
        { entityName: '&curren;', entityNumber: 164, description: 'Currency sign' },
        { entityName: '&yen;', entityNumber: 165, description: 'Yen currency sign' },
        { entityName: '&brvbar;', entityNumber: 166, description: 'Broken vertical bar' },
        { entityName: '&sect;', entityNumber: 167, description: 'Section symbol' },
        { entityName: '&uml;', entityNumber: 168, description: 'Umlaut (Diaeresis)' },
        { entityName: '&copy;', entityNumber: 169, description: 'Copyright' },
        { entityName: '&ordf;', entityNumber: 170, description: 'Feminine ordinal indicator (superscript lowercase a)' },
        { entityName: '&laquo;', entityNumber: 171, description: 'Left angle quote' },
        { entityName: '&not;', entityNumber: 172, description: 'Not sign' },
        { entityName: '&shy;', entityNumber: 173, description: 'Soft hyphen' },
        { entityName: '&reg;', entityNumber: 174, description: 'Registered sign' },
        { entityName: '&macr;', entityNumber: 175, description: 'Macron' },
        { entityName: '&deg;', entityNumber: 176, description: 'Degree sign' },
        { entityName: '&plusmn;', entityNumber: 177, description: 'Plus/minus sign' },
        { entityName: '&sup2;', entityNumber: 178, description: 'Superscript 2' },
        { entityName: '&sup3;', entityNumber: 179, description: 'Superscript 3' },
        { entityName: '', entityNumber: 180, description: 'Acute accent' },
        { entityName: '&micro;', entityNumber: 181, description: 'Micro sign' },
        { entityName: '&para;', entityNumber: 182, description: 'Pilcrow sign (paragraph)' },
        { entityName: '&middot;', entityNumber: 183, description: 'Middle dot' },
        { entityName: '&cedil;', entityNumber: 184, description: 'Cedilla' },
        { entityName: '&sup1;', entityNumber: 185, description: 'Superscript 1' },
        { entityName: '&ordm;', entityNumber: 186, description: 'Masculine ordinal indicator (superscript o)' },
        { entityName: '&raquo;', entityNumber: 187, description: 'Right angle quote' },
        { entityName: '&frac14;', entityNumber: 188, description: 'One quarter fraction' },
        { entityName: '&frac12;', entityNumber: 189, description: 'One half fraction' },
        { entityName: '&frac34;', entityNumber: 190, description: 'Three quarters fraction' },
        { entityName: '&iquest;', entityNumber: 191, description: 'Inverted question mark' },
        { entityName: '&Agrave;', entityNumber: 192, description: 'A grave accent' },
        { entityName: '&Aacute;', entityNumber: 193, description: 'A accute accent' },
        { entityName: '&Acirc;', entityNumber: 194, description: 'A circumflex' },
        { entityName: '&Atilde;', entityNumber: 195, description: 'A tilde' },
        { entityName: '&Auml;', entityNumber: 196, description: 'A umlaut' },
        { entityName: '&Aring;', entityNumber: 197, description: 'A ring' },
        { entityName: '&AElig;', entityNumber: 198, description: 'AE ligature' },
        { entityName: '&Ccedil;', entityNumber: 199, description: 'C cedilla' },
        { entityName: '&Egrave;', entityNumber: 200, description: 'E grave' },
        { entityName: '&Eacute;', entityNumber: 201, description: 'E acute' },
        { entityName: '&Ecirc;', entityNumber: 202, description: 'E circumflex' },
        { entityName: '&Euml;', entityNumber: 203, description: 'E umlaut' },
        { entityName: '&Igrave;', entityNumber: 204, description: 'I grave' },
        { entityName: '&Iacute;', entityNumber: 205, description: 'I acute' },
        { entityName: '&Icirc;', entityNumber: 206, description: 'I circumflex' },
        { entityName: '&Iuml;', entityNumber: 207, description: 'I umlaut' },
        { entityName: '&ETH;', entityNumber: 208, description: 'Eth' },
        { entityName: '&Ntilde;', entityNumber: 209, description: 'N tilde (enye)' },
        { entityName: '&Ograve;', entityNumber: 210, description: 'O grave' },
        { entityName: '&Oacute;', entityNumber: 211, description: 'O acute' },
        { entityName: '&Ocirc;', entityNumber: 212, description: 'O circumflex' },
        { entityName: '&Otilde;', entityNumber: 213, description: 'O tilde' },
        { entityName: '&Ouml;', entityNumber: 214, description: 'O umlaut' },
        { entityName: '&times;', entityNumber: 215, description: 'Multiplication sign' },
        { entityName: '&Oslash;', entityNumber: 216, description: 'O slash' },
        { entityName: '&Ugrave;', entityNumber: 217, description: 'U grave' },
        { entityName: '&Uacute;', entityNumber: 218, description: 'U acute' },
        { entityName: '&Ucirc;', entityNumber: 219, description: 'U circumflex' },
        { entityName: '&Uuml;', entityNumber: 220, description: 'U umlaut' },
        { entityName: '&Yacute;', entityNumber: 221, description: 'Y acute' },
        { entityName: '&THORN;', entityNumber: 222, description: 'Thorn' },
        { entityName: '&szlig;', entityNumber: 223, description: 'SZ ligature' },
        { entityName: '&agrave;', entityNumber: 224, description: 'a grave' },
        { entityName: '&aacute;', entityNumber: 225, description: 'a acute' },
        { entityName: '&acirc;', entityNumber: 226, description: 'a circumflex' },
        { entityName: '&atilde;', entityNumber: 227, description: 'a tilde' },
        { entityName: '&auml;', entityNumber: 228, description: 'a umlaut' },
        { entityName: '&aring;', entityNumber: 229, description: 'a ring' },
        { entityName: '&aelig;', entityNumber: 230, description: 'ae ligature' },
        { entityName: '&ccedil;', entityNumber: 231, description: 'c cedilla' },
        { entityName: '&egrave;', entityNumber: 232, description: 'e grave' },
        { entityName: '&eacute;', entityNumber: 233, description: 'e acute' },
        { entityName: '&ecirc;', entityNumber: 234, description: 'e circumflex' },
        { entityName: '&euml;', entityNumber: 235, description: 'e umlaut' },
        { entityName: '&igrave;', entityNumber: 236, description: 'i grave' },
        { entityName: '&iacute;', entityNumber: 237, description: 'i acute' },
        { entityName: '&icirc;', entityNumber: 238, description: 'i circumflex' },
        { entityName: '&iuml;', entityNumber: 239, description: 'i umlaut' },
        { entityName: '&eth;', entityNumber: 240, description: 'eth' },
        { entityName: '&ntilde;', entityNumber: 241, description: 'n tilde' },
        { entityName: '&ograve;', entityNumber: 242, description: 'o grave' },
        { entityName: '&oacute;', entityNumber: 243, description: 'o acute' },
        { entityName: '&ocirc;', entityNumber: 244, description: 'o circumflex' },
        { entityName: '&otilde;', entityNumber: 245, description: 'o tilde' },
        { entityName: '&ouml;', entityNumber: 246, description: 'o umlaut' },
        { entityName: '&divide;', entityNumber: 247, description: 'Division symbol' },
        { entityName: '&oslash;', entityNumber: 248, description: 'o slash' },
        { entityName: '&ugrave;', entityNumber: 249, description: 'u grave' },
        { entityName: '&uacute;', entityNumber: 250, description: 'u acute' },
        { entityName: '&ucirc;', entityNumber: 251, description: 'u circumflex' },
        { entityName: '&uuml;', entityNumber: 252, description: 'u umlaut' },
        { entityName: '&yacute;', entityNumber: 253, description: 'y acute' },
        { entityName: '&thorn;', entityNumber: 254, description: 'thorn' },
        { entityName: '&yuml;', entityNumber: 255, description: 'y umlaut' },
    ]
}
export function getDiacritics(): CharacterData[] {
    return [
        { entityName: '', entityNumber: 96, description: 'Grave Accent' },
        { entityName: '', entityNumber: 136, description: 'Hachek' },
        { entityName: '&tilde;', entityNumber: 152, description: 'Tilde' },
        { entityName: '&uml;', entityNumber: 168, description: 'Umlaut' },
        { entityName: '&macr;', entityNumber: 175, description: 'Macron' },
        { entityName: '&acute;', entityNumber: 180, description: 'Acute' },
        { entityName: '&cedil;', entityNumber: 184, description: 'Cedilla' },
        { entityName: '', entityNumber: 728, description: 'Breve' },
        { entityName: '', entityNumber: 729, description: 'Dot' },
        { entityName: '', entityNumber: 730, description: 'Ring' },
        { entityName: '', entityNumber: 731, description: 'Ring' },
        { entityName: '', entityNumber: 732, description: 'Small Tilde' },
        { entityName: '', entityNumber: 733, description: 'Double Accent' },
    ]
}
export function getMathematical(): CharacterData[] {
    return [
        { entityName: '', entityNumber: 8722, description: 'Minus Sign' },
        { entityName: '+', entityNumber: 43, description: 'Plus Sign' },
        { entityName: '&plusmn;', entityNumber: 177, description: 'Plus or Minus Sign' },
        { entityName: '&times;', entityNumber: 215, description: 'Multiplication Sign' },
        { entityName: '&divide;', entityNumber: 247, description: 'Division Sign' },
        { entityName: '%', entityNumber: 37, description: 'Percent Sign' },
        { entityName: '', entityNumber: 137, description: 'Per Mille Sign (per thousand)' },
        { entityName: '=', entityNumber: 61, description: 'Equal Sign' },
        { entityName: '', entityNumber: 8800, description: 'Not Equal To Sign' },
        { entityName: '', entityNumber: 8776, description: 'Approximately Equal Sign' },
        { entityName: '', entityNumber: 8801, description: 'Identical To Sign' },
        { entityName: '&lt;', entityNumber: 60, description: 'Less Than Sign' },
        { entityName: '&gt;', entityNumber: 62, description: 'Greater Than Sign' },
        { entityName: '', entityNumber: 8804, description: 'Less Than or Equal To Sign' },
        { entityName: '', entityNumber: 8805, description: 'Greater Than or Equal To Sign' },
        { entityName: '', entityNumber: 8734, description: 'Infinity Sign' },
        { entityName: '', entityNumber: 8539, description: 'One Eighth Fraction' },
        { entityName: '&frac14;', entityNumber: 188, description: 'One Quarter Fraction' },
        { entityName: '', entityNumber: 8540, description: 'Three Eighths Fraction' },
        { entityName: '&frac12;', entityNumber: 189, description: 'One Half Fraction' },
        { entityName: '', entityNumber: 8541, description: 'Five Eighths Fraction' },
        { entityName: '&frac34;', entityNumber: 190, description: 'Three Quarters Fraction' },
        { entityName: '', entityNumber: 8542, description: 'Seven Eighths Fraction' },
        { entityName: '', entityNumber: 8747, description: 'Integral Sign' },
        { entityName: '', entityNumber: 8706, description: 'Partial Differential Sign' },
        { entityName: '', entityNumber: 8710, description: 'Increment Sign' },
        { entityName: '', entityNumber: 8719, description: 'N-ary Product Sign' },
        { entityName: '', entityNumber: 8721, description: 'N-ary Sum Sign' },
        { entityName: '', entityNumber: 8730, description: 'Square Root Sign' },
        { entityName: '', entityNumber: 8735, description: 'Right Angle Sign' },
        { entityName: '', entityNumber: 8745, description: 'Intersection Sign' },
        { entityName: '', entityNumber: 8729, description: 'Bullet Operator' },
        { entityName: '', entityNumber: 131, description: 'Function Sign' },
        { entityName: '', entityNumber: 8260, description: 'Fraction Slash' },
    ]
}
export function getCurrencies(): CharacterData[] {
    return [
        { entityName: '$', entityNumber: 36, description: 'Dollar Sign' },
        { entityName: '&euro;', entityNumber: 128, description: 'Euro Symbol' },
        { entityName: '&pound;', entityNumber: 163, description: 'Pound Sterling' },
        { entityName: '&yen;', entityNumber: 165, description: 'Yen Symbol' },
        { entityName: '&cent;', entityNumber: 162, description: 'Cent Sign' },
        { entityName: '', entityNumber: 8355, description: 'Franc Sign' },
        { entityName: '', entityNumber: 8356, description: 'Lira Symbol' },
        { entityName: '', entityNumber: 8359, description: 'Peseta Sign' },
        { entityName: '&curren;', entityNumber: 164, description: 'Generic Currency Symbol' },
        { entityName: '%', entityNumber: 37, description: 'Percent' },
        { entityName: '', entityNumber: 137, description: 'Per Thousand' },
    ]
}
export function getPunctuations(): CharacterData[] {
    return [
        { entityName: '', entityNumber: 9, description: 'Horizontal Tab' },
        { entityName: '', entityNumber: 10, description: 'Line Feed' },
        { entityName: '', entityNumber: 32, description: 'Space' },
        { entityName: '!', entityNumber: 33, description: 'Exclamation Point' },
        { entityName: '&quot;', entityNumber: 34, description: 'Double Quote' },
        { entityName: '#', entityNumber: 35, description: 'Number Sign' },
        { entityName: '&amp;', entityNumber: 38, description: 'Ampersand' },
        { entityName: '\'', entityNumber: 39, description: 'Single Quote' },
        { entityName: '(', entityNumber: 40, description: 'Left Parenthesis' },
        { entityName: ')', entityNumber: 41, description: 'Right Parenthesis' },
        { entityName: '*', entityNumber: 42, description: 'Asterisk (Star)' },
        { entityName: ',', entityNumber: 44, description: 'Comma' },
        { entityName: '-', entityNumber: 45, description: 'Hyphen' },
        { entityName: '.', entityNumber: 46, description: 'Period' },
        { entityName: '/', entityNumber: 47, description: 'Forward Slash' },
        { entityName: ':', entityNumber: 58, description: 'Colon' },
        { entityName: ';', entityNumber: 59, description: 'Semi-Colon' },
        { entityName: '?', entityNumber: 63, description: 'Question Mark' },
        { entityName: '@', entityNumber: 64, description: 'At Sign' },
        { entityName: '[', entityNumber: 91, description: 'Left Square Bracket' },
        { entityName: '\\', entityNumber: 92, description: 'Back Slash' },
        { entityName: ']', entityNumber: 93, description: 'Right Square Bracket' },
        { entityName: '^', entityNumber: 94, description: 'Caret' },
        { entityName: '_', entityNumber: 95, description: 'Underscore' },
        { entityName: '{', entityNumber: 123, description: 'Left Curly Brace' },
        { entityName: '|', entityNumber: 124, description: 'Vertical Bar' },
        { entityName: '}', entityNumber: 125, description: 'Right Curly Brace' },
        { entityName: '&tilde;', entityNumber: 126, description: 'Vertical Bar' },
        { entityName: '&sbquo;', entityNumber: 130, description: 'Single Low Quote' },
        { entityName: '&dbquo;', entityNumber: 132, description: 'Double Low Quote' },
        { entityName: '', entityNumber: 133, description: 'Elipsis' },
        { entityName: '&dagger;', entityNumber: 134, description: 'Dagger' },
        { entityName: '&Dagger;', entityNumber: 135, description: 'Double Dagger' },
        { entityName: '&lsaquo;', entityNumber: 139, description: 'Left Single Angle Quote' },
        { entityName: '&lsquo;', entityNumber: 145, description: 'Left Single Quote' },
        { entityName: '&rsquo;', entityNumber: 146, description: 'Right Single Quote' },
        { entityName: '&ldquo;', entityNumber: 147, description: 'Left Double Quote' },
        { entityName: '&rdquo;', entityNumber: 148, description: 'Right Double Quote' },
        { entityName: '', entityNumber: 149, description: 'Small Bullet' },
        { entityName: '&ndash;', entityNumber: 150, description: 'En Dash' },
        { entityName: '&mdash;', entityNumber: 151, description: 'Em Dash' },
        { entityName: '&trade;', entityNumber: 153, description: 'Trademark' },
        { entityName: '&rsaquo;', entityNumber: 155, description: 'Right Single Angle Quote' },
        { entityName: '&nbsp;', entityNumber: 160, description: 'Non-Breaking Space' },
        { entityName: '&iexcl;', entityNumber: 161, description: 'Inverted Exclamation Point' },
        { entityName: '&brvbar;', entityNumber: 166, description: 'Broken Vertical Bar' },
        { entityName: '&sect;', entityNumber: 167, description: 'Section Mark' },
        { entityName: '&copy;', entityNumber: 169, description: 'Copyright' },
        { entityName: '&ordf;', entityNumber: 170, description: 'Feminine Ordinal Indicator' },
        { entityName: '&laquo;', entityNumber: 171, description: 'Left Angle Quote' },
        { entityName: '&not;', entityNumber: 172, description: 'Not Sign' },
        { entityName: '&shy;', entityNumber: 173, description: 'Soft Hyphen' },
        { entityName: '&reg;', entityNumber: 174, description: 'Registered Symbol' },
        { entityName: '&deg;', entityNumber: 176, description: 'Degree' },
        { entityName: '&sup2;', entityNumber: 178, description: 'Superscript 2' },
        { entityName: '&sup3;', entityNumber: 179, description: 'Superscript 3' },
        { entityName: '&micro;', entityNumber: 181, description: 'Micro Sign' },
        { entityName: '&para;', entityNumber: 182, description: 'Pilcrow (Paragraph Sign)' },
        { entityName: '&middot;', entityNumber: 183, description: 'Middle Dot' },
        { entityName: '&sup1;', entityNumber: 185, description: 'Superscript 1' },
        { entityName: '&ordm;', entityNumber: 186, description: 'Masculine Ordinal Indicator' },
        { entityName: '&raquo;', entityNumber: 187, description: 'Right Angle Quote' },
        { entityName: '&iquest;', entityNumber: 191, description: 'Inverted Question Mark' },
        { entityName: '', entityNumber: 8453, description: 'Care Of' },
        { entityName: '', entityNumber: 8319, description: 'Superscript N' },
        { entityName: '', entityNumber: 8213, description: 'Horizontal Bar' },
        { entityName: '', entityNumber: 8227, description: 'Triangle Bullet' },
        { entityName: '&oline;', entityNumber: 8254, description: 'Overline' },
        { entityName: '', entityNumber: 8252, description: 'Double Exclamation Point' },
        { entityName: '', entityNumber: 8470, description: 'Number Word' },
    ]
}

export function getLetters(): CharacterData[] {
    return [
        { entityName: 'A', entityNumber: 65, description: 'Capital A' },
        { entityName: 'a', entityNumber: 97, description: 'Lowercase A' },
        { entityName: '&Agrave;', entityNumber: 192, description: 'Capital A-grave' },
        { entityName: '&agrave;', entityNumber: 224, description: 'Lowercase A-grave' },
        { entityName: '&Aacute;', entityNumber: 193, description: 'Capital A-acute' },
        { entityName: '&aacute;', entityNumber: 225, description: 'Lowercase A-acute' },
        { entityName: '&Acirc;', entityNumber: 194, description: 'Capital A-circumflex' },
        { entityName: '&acirc;', entityNumber: 226, description: 'Lowercase A-circumflex' },
        { entityName: '&Atilde;', entityNumber: 195, description: 'Capital A-tilde' },
        { entityName: '&atilde;', entityNumber: 227, description: 'Lowercase A-tilde' },
        { entityName: '&Auml;', entityNumber: 196, description: 'Capital A-umlaut' },
        { entityName: '&auml;', entityNumber: 228, description: 'Lowercase A-umlaut' },
        { entityName: '&Aring;', entityNumber: 197, description: 'Capital A-ring' },
        { entityName: '&aring;', entityNumber: 229, description: 'Lowercase A-umlaut' },
        { entityName: '', entityNumber: 256, description: 'Capital A-macron' },
        { entityName: '', entityNumber: 257, description: 'Lowercase A-macron' },
        { entityName: '', entityNumber: 258, description: 'Capital A-breve' },
        { entityName: '', entityNumber: 259, description: 'Lowercase A-breve' },
        { entityName: '', entityNumber: 260, description: 'Capital A-ogonek' },
        { entityName: '', entityNumber: 261, description: 'Lowercase A-ogonek' },
        { entityName: '', entityNumber: 478, description: 'Capital A-diaeresis and macron' },
        { entityName: '', entityNumber: 479, description: 'Lowercase A-diaeresis and macron' },
        { entityName: '', entityNumber: 506, description: 'Capital A-acute ring' },
        { entityName: '', entityNumber: 507, description: 'Lowercase A-acute ring' },
        { entityName: '&AElig;', entityNumber: 198, description: 'Capital AE Ligature' },
        { entityName: '&aelig;', entityNumber: 230, description: 'Lowercase AE Ligature' },
        { entityName: '', entityNumber: 508, description: 'Capital AE Ligature-acute' },
        { entityName: '', entityNumber: 509, description: 'Lowercase AE Ligature-acute' },
        { entityName: 'B', entityNumber: 66, description: 'Capital B' },
        { entityName: 'b', entityNumber: 98, description: 'Lowercase B' },
        { entityName: '', entityNumber: 7682, description: 'Capital B-dot' },
        { entityName: '', entityNumber: 7683, description: 'Lowercase B-dot' },
        { entityName: 'C', entityNumber: 67, description: 'Capital C' },
        { entityName: 'c', entityNumber: 99, description: 'Lowercase C' },
        { entityName: '', entityNumber: 262, description: 'Capital C-acute' },
        { entityName: '', entityNumber: 263, description: 'Lowercase C-acute' },
        { entityName: '&Ccedil;', entityNumber: 199, description: 'Capital C-cedilla' },
        { entityName: '&ccedil;', entityNumber: 231, description: 'Lowercase C-cedilla' },
        { entityName: '', entityNumber: 268, description: 'Capital C-hachek' },
        { entityName: '', entityNumber: 269, description: 'Lowercase C-hachek' },
        { entityName: '', entityNumber: 264, description: 'Capital C-circumflex' },
        { entityName: '', entityNumber: 265, description: 'Lowercase C-circumflex' },
        { entityName: '', entityNumber: 266, description: 'Capital C-dot' },
        { entityName: '', entityNumber: 267, description: 'Lowercase C-dot' },
        { entityName: 'D', entityNumber: 68, description: 'Capital D' },
        { entityName: 'd', entityNumber: 100, description: 'Lowercase D' },
        { entityName: '', entityNumber: 7696, description: 'Capital D-cedilla' },
        { entityName: '', entityNumber: 7697, description: 'Lowercase D-cedilla' },
        { entityName: '', entityNumber: 270, description: 'Capital D-hachek' },
        { entityName: '', entityNumber: 271, description: 'Lowercase D-hachek' },
        { entityName: '', entityNumber: 7690, description: 'Capital D-dot' },
        { entityName: '', entityNumber: 7691, description: 'Lowercase D-dot' },
        { entityName: '', entityNumber: 272, description: 'Capital D-stroke' },
        { entityName: '', entityNumber: 273, description: 'Lowercase D-stroke' },
        { entityName: '&ETH;', entityNumber: 208, description: 'Capital Eth (Icelandic)' },
        { entityName: '&eth;', entityNumber: 240, description: 'Lowercase Eth (Icelandic)' },
        { entityName: '', entityNumber: 497, description: 'Capital DZ Ligature' },
        { entityName: '', entityNumber: 498, description: 'Capital DZ Ligature' },
        { entityName: '', entityNumber: 499, description: 'Lowercase DZ Ligature' },
        { entityName: '', entityNumber: 452, description: 'Capital DZ-hachek' },
        { entityName: '', entityNumber: 453, description: 'Capital DZ-hachek' },
        { entityName: '', entityNumber: 454, description: 'Lowercase DZ-hachek' },
        { entityName: 'E', entityNumber: 69, description: 'Capital E' },
        { entityName: 'e', entityNumber: 101, description: 'Lowercase E' },
        { entityName: '&Egrave;', entityNumber: 200, description: 'Capital E-grave' },
        { entityName: '&egrave;', entityNumber: 232, description: 'Lowercase E-grave' },
        { entityName: '&Eacute;', entityNumber: 201, description: 'Capital E-acute' },
        { entityName: '&eacute;', entityNumber: 233, description: 'Lowercase E-acute' },
        { entityName: '', entityNumber: 282, description: 'Capital E-hachek' },
        { entityName: '', entityNumber: 283, description: 'Lowercase E-hachek' },
        { entityName: '&Ecirc;', entityNumber: 202, description: 'Capital E-circumflex' },
        { entityName: '&ecirc;', entityNumber: 234, description: 'Lowercase E-circumflex' },
        { entityName: '&Euml;', entityNumber: 203, description: 'Capital E-umlaut' },
        { entityName: '&euml;', entityNumber: 235, description: 'Lowercase E-umlaut' },
        { entityName: '', entityNumber: 274, description: 'Capital E-macron' },
        { entityName: '', entityNumber: 275, description: 'Lowercase E-macron' },
        { entityName: '', entityNumber: 276, description: 'Capital E-breve' },
        { entityName: '', entityNumber: 277, description: 'Lowercase E-breve' },
        { entityName: '', entityNumber: 280, description: 'Capital E-ogonek' },
        { entityName: '', entityNumber: 281, description: 'Lowercase E-ogonek' },
        { entityName: '', entityNumber: 278, description: 'Capital E-dot' },
        { entityName: '', entityNumber: 279, description: 'Lowercase E-dot' },
        { entityName: '', entityNumber: 439, description: 'Capital Ezh' },
        { entityName: '', entityNumber: 658, description: 'Lowercase Ezh' },
        { entityName: '', entityNumber: 494, description: 'Capital Ezh-hachek' },
        { entityName: '', entityNumber: 495, description: 'Lowercase Ezh-hachek' },
        { entityName: 'F', entityNumber: 70, description: 'Capital F' },
        { entityName: 'f', entityNumber: 102, description: 'Lowercase F' },
        { entityName: '', entityNumber: 7710, description: 'Capital F-dot' },
        { entityName: '', entityNumber: 7711, description: 'Lowercase F-dot' },
        { entityName: '', entityNumber: 402, description: 'Lowercase F-hook' },
        { entityName: '', entityNumber: 64256, description: 'Lowercase FF Ligature' },
        { entityName: '', entityNumber: 64257, description: 'Lowercase FI Ligature' },
        { entityName: '', entityNumber: 64258, description: 'Lowercase FL Ligature' },
        { entityName: '', entityNumber: 64259, description: 'Lowercase FFI Ligature' },
        { entityName: '', entityNumber: 64260, description: 'Lowercase FFL Ligature' },
        { entityName: '', entityNumber: 64261, description: 'Lowercase FT Ligature' },
        { entityName: 'G', entityNumber: 71, description: 'Capital G' },
        { entityName: 'g', entityNumber: 103, description: 'Lowercase G' },
        { entityName: '', entityNumber: 500, description: 'Capital G-acute' },
        { entityName: '', entityNumber: 501, description: 'Lowercase G-acute' },
        { entityName: '', entityNumber: 290, description: 'Capital G-cedilla' },
        { entityName: '', entityNumber: 291, description: 'Lowercase G-cedilla' },
        { entityName: '', entityNumber: 486, description: 'Capital G-hachek' },
        { entityName: '', entityNumber: 487, description: 'Lowercase G-hachek' },
        { entityName: '', entityNumber: 284, description: 'Capital G-circumflex' },
        { entityName: '', entityNumber: 285, description: 'Lowercase G-circumflex' },
        { entityName: '', entityNumber: 286, description: 'Capital G-breve' },
        { entityName: '', entityNumber: 287, description: 'Lowercase G-breve' },
        { entityName: '', entityNumber: 288, description: 'Capital G-dot' },
        { entityName: '', entityNumber: 289, description: 'Lowercase G-dot' },
        { entityName: '', entityNumber: 484, description: 'Capital G-stroke' },
        { entityName: '', entityNumber: 485, description: 'Lowercase G-stroke' },
        { entityName: 'H', entityNumber: 72, description: 'Capital H' },
        { entityName: 'h', entityNumber: 104, description: 'Lowercase H' },
        { entityName: '', entityNumber: 292, description: 'Capital H-circumflex' },
        { entityName: '', entityNumber: 293, description: 'Lowercase H-circumflex' },
        { entityName: '', entityNumber: 294, description: 'Capital H-stroke' },
        { entityName: '', entityNumber: 295, description: 'Lowercase H-stroke' },
        { entityName: 'I', entityNumber: 73, description: 'Capital I' },
        { entityName: 'i', entityNumber: 105, description: 'Lowercase I' },
        { entityName: '&Igrave;', entityNumber: 204, description: 'Capital I-grave' },
        { entityName: '&igrave;', entityNumber: 236, description: 'Lowercase I-grave' },
        { entityName: '&Iacute;', entityNumber: 205, description: 'Capital I-acute' },
        { entityName: '&iacute;', entityNumber: 237, description: 'Lowercase I-acute' },
        { entityName: '&Icirc;', entityNumber: 206, description: 'Capital I-circumflex' },
        { entityName: '&icirc;', entityNumber: 238, description: 'Lowercase I-circumflex' },
        { entityName: '', entityNumber: 296, description: 'Capital I-tilde' },
        { entityName: '', entityNumber: 297, description: 'Lowercase I-tilde' },
        { entityName: '&Iuml;', entityNumber: 207, description: 'Capital I-umlaut' },
        { entityName: '&iuml;', entityNumber: 239, description: 'Lowercase I-umlaut' },
        { entityName: '', entityNumber: 298, description: 'Capital I-macron' },
        { entityName: '', entityNumber: 299, description: 'Lowercase I-macron' },
        { entityName: '', entityNumber: 300, description: 'Capital I-breve' },
        { entityName: '', entityNumber: 301, description: 'Lowercase I-breve' },
        { entityName: '', entityNumber: 302, description: 'Capital I-ogonek' },
        { entityName: '', entityNumber: 303, description: 'Lowercase I-ogonek' },
        { entityName: '', entityNumber: 304, description: 'Capital I-dot' },
        { entityName: '', entityNumber: 305, description: 'Lowercase I-dotless' },
        { entityName: '', entityNumber: 306, description: 'Capital IJ Ligature' },
        { entityName: '', entityNumber: 307, description: 'Lowercase IJ Ligature' },
        { entityName: 'J', entityNumber: 74, description: 'Capital J' },
        { entityName: 'j', entityNumber: 106, description: 'Lowercase J' },
        { entityName: '', entityNumber: 308, description: 'Capital J-circumflex' },
        { entityName: '', entityNumber: 309, description: 'Lowercase J-circumflex' },
        { entityName: 'K', entityNumber: 75, description: 'Capital K' },
        { entityName: 'k', entityNumber: 107, description: 'Lowercase K' },
        { entityName: '', entityNumber: 7728, description: 'Capital K-acute' },
        { entityName: '', entityNumber: 7729, description: 'Lowercase K-acute' },
        { entityName: '', entityNumber: 310, description: 'Capital K-cedilla' },
        { entityName: '', entityNumber: 311, description: 'Lowercase K-cedilla' },
        { entityName: '', entityNumber: 488, description: 'Capital K-hachek' },
        { entityName: '', entityNumber: 489, description: 'Lowercase K-hachek' },
        { entityName: '', entityNumber: 312, description: 'Small Capital K' },
        { entityName: 'L', entityNumber: 76, description: 'Capital L' },
        { entityName: 'l', entityNumber: 108, description: 'Lowercase L' },
        { entityName: '', entityNumber: 313, description: 'Capital L-acute' },
        { entityName: '', entityNumber: 314, description: 'Lowercase L-acute' },
        { entityName: '', entityNumber: 315, description: 'Capital L-cedilla' },
        { entityName: '', entityNumber: 316, description: 'Lowercase L-cedilla' },
        { entityName: '', entityNumber: 317, description: 'Capital L-hachek' },
        { entityName: '', entityNumber: 318, description: 'Lowercase L-hachek' },
        { entityName: '', entityNumber: 319, description: 'Capital L-middle dot' },
        { entityName: '', entityNumber: 320, description: 'Lowercase L-middle dot' },
        { entityName: '', entityNumber: 321, description: 'Capital L-stroke' },
        { entityName: '', entityNumber: 322, description: 'Lowercase L-stroke' },
        { entityName: '', entityNumber: 455, description: 'Capital LJ Ligature' },
        { entityName: '', entityNumber: 456, description: 'Capital LJ Ligature' },
        { entityName: '', entityNumber: 457, description: 'Lowercase LJ Ligature' },
        { entityName: 'M', entityNumber: 77, description: 'Capital M' },
        { entityName: 'm', entityNumber: 109, description: 'Lowercase M' },
        { entityName: '', entityNumber: 7744, description: 'Capital M-dot' },
        { entityName: '', entityNumber: 7745, description: 'Lowercase M-dot' },
        { entityName: 'N', entityNumber: 78, description: 'Capital N' },
        { entityName: 'n', entityNumber: 110, description: 'Lowercase N' },
        { entityName: '', entityNumber: 323, description: 'Capital N-acute' },
        { entityName: '', entityNumber: 324, description: 'Lowercase N-acute' },
        { entityName: '', entityNumber: 325, description: 'Capital N-cedilla' },
        { entityName: '', entityNumber: 326, description: 'Lowercase N-cedilla' },
        { entityName: '', entityNumber: 327, description: 'Capital N-hachek' },
        { entityName: '', entityNumber: 328, description: 'Lowercase N-hachek' },
        { entityName: '&Ntilde;', entityNumber: 209, description: 'Capital N-tilde' },
        { entityName: '&ntilde;', entityNumber: 241, description: 'Lowercase N-tilde' },
        { entityName: '', entityNumber: 329, description: 'Lowercase N-apostrophe (before)' },
        { entityName: '', entityNumber: 330, description: 'Capital Eng' },
        { entityName: '', entityNumber: 331, description: 'Lowercase Eng' },
        { entityName: '', entityNumber: 458, description: 'Capital NJ Ligature' },
        { entityName: '', entityNumber: 459, description: 'Capital NJ Ligature' },
        { entityName: '', entityNumber: 460, description: 'Lowercase NJ Ligature' },
        { entityName: 'O', entityNumber: 79, description: 'Capital O' },
        { entityName: 'o', entityNumber: 111, description: 'Lowercase O' },
        { entityName: '&Ograve;', entityNumber: 210, description: 'Capital O-grave' },
        { entityName: '&ograve;', entityNumber: 242, description: 'Lowercase O-grave' },
        { entityName: '&Oacute;', entityNumber: 211, description: 'Capital O-acute' },
        { entityName: '&oacute;', entityNumber: 243, description: 'Lowercase O-acute' },
        { entityName: '&Ocirc;', entityNumber: 212, description: 'Capital O-circumflex' },
        { entityName: '&ocirc;', entityNumber: 244, description: 'Lowercase O-circumflex' },
        { entityName: '&Otilde;', entityNumber: 213, description: 'Capital O-tilde' },
        { entityName: '&otilde;', entityNumber: 245, description: 'Lowercase O-tilde' },
        { entityName: '&Ouml;', entityNumber: 214, description: 'Capital O-umlaut' },
        { entityName: '&ouml;', entityNumber: 246, description: 'Lowercase O-umlaut' },
        { entityName: '', entityNumber: 332, description: 'Capital O-macron' },
        { entityName: '', entityNumber: 333, description: 'Lowercase O-macron' },
        { entityName: '', entityNumber: 334, description: 'Capital O-breve' },
        { entityName: '', entityNumber: 335, description: 'Lowercase O-breve' },
        { entityName: '&Oslash;', entityNumber: 216, description: 'Capital O-slash' },
        { entityName: '&oslash;', entityNumber: 248, description: 'Lowercase O-slash' },
        { entityName: '', entityNumber: 336, description: 'Capital O-double acute' },
        { entityName: '', entityNumber: 337, description: 'Lowercase O-double acute' },
        { entityName: '', entityNumber: 510, description: 'Capital O-acute slash' },
        { entityName: '', entityNumber: 511, description: 'Lowercase O-acute slash' },
        { entityName: '&OElig;', entityNumber: 338, description: 'Capital OE Ligature' },
        { entityName: '&oelig;', entityNumber: 339, description: 'Lowercase OE Ligature' },
        { entityName: 'P', entityNumber: 80, description: 'Capital P' },
        { entityName: 'p', entityNumber: 112, description: 'Lowercase P' },
        { entityName: '', entityNumber: 7766, description: 'Capital P-dot' },
        { entityName: '', entityNumber: 7767, description: 'Lowercase P-dot' },
        { entityName: 'Q', entityNumber: 81, description: 'Capital Q' },
        { entityName: 'q', entityNumber: 113, description: 'Lowercase Q' },
        { entityName: 'R', entityNumber: 82, description: 'Capital R' },
        { entityName: 'r', entityNumber: 114, description: 'Lowercase R' },
        { entityName: '', entityNumber: 340, description: 'Capital R-acute' },
        { entityName: '', entityNumber: 341, description: 'Lowercase R-acute' },
        { entityName: '', entityNumber: 342, description: 'Capital R-cedilla' },
        { entityName: '', entityNumber: 343, description: 'Lowercase R-cedilla' },
        { entityName: '', entityNumber: 344, description: 'Capital R-hachek' },
        { entityName: '', entityNumber: 345, description: 'Lowercase R-hachek' },
        { entityName: '', entityNumber: 636, description: 'Lowercase R-Long leg' },
        { entityName: 'S', entityNumber: 83, description: 'Capital S' },
        { entityName: 's', entityNumber: 115, description: 'Lowercase S' },
        { entityName: '', entityNumber: 346, description: 'Capital S-acute' },
        { entityName: '', entityNumber: 347, description: 'Lowercase S-acute' },
        { entityName: '', entityNumber: 350, description: 'Capital S-cedilla' },
        { entityName: '', entityNumber: 351, description: 'Lowercase S-cedilla' },
        { entityName: '', entityNumber: 352, description: 'Capital S-hachek' },
        { entityName: '', entityNumber: 353, description: 'Lowercase S-hachek' },
        { entityName: '', entityNumber: 348, description: 'Capital S-circumflex' },
        { entityName: '', entityNumber: 349, description: 'Lowercase S-circumflex' },
        { entityName: '', entityNumber: 7776, description: 'Capital S-dot' },
        { entityName: '', entityNumber: 7777, description: 'Lowercase S-dot' },
        { entityName: '', entityNumber: 383, description: 'Lowercase S-long' },
        { entityName: '&szlig;', entityNumber: 223, description: 'Lowercase SZ Ligature' },
        { entityName: 'T', entityNumber: 84, description: 'Capital T' },
        { entityName: 't', entityNumber: 116, description: 'Lowercase T' },
        { entityName: '', entityNumber: 354, description: 'Capital T-cedilla' },
        { entityName: '', entityNumber: 355, description: 'Lowercase T-cedilla' },
        { entityName: '', entityNumber: 356, description: 'Capital T-hachek' },
        { entityName: '', entityNumber: 357, description: 'Lowercase T-hachek' },
        { entityName: '', entityNumber: 7786, description: 'Capital T-dot' },
        { entityName: '', entityNumber: 7787, description: 'Lowercase T-dot' },
        { entityName: '', entityNumber: 358, description: 'Capital T-stroke' },
        { entityName: '', entityNumber: 359, description: 'Lowercase T-stroke' },
        { entityName: '&THORN;', entityNumber: 222, description: 'Capital Thorn' },
        { entityName: '&thorn;', entityNumber: 254, description: 'Lowercase Thorn' },
        { entityName: 'U', entityNumber: 85, description: 'Capital U' },
        { entityName: 'u', entityNumber: 117, description: 'Lowercase U' },
        { entityName: '&Ugrave;', entityNumber: 217, description: 'Capital U-grave' },
        { entityName: '&ugrave;', entityNumber: 249, description: 'Lowercase U-grave' },
        { entityName: '&Uacute;', entityNumber: 218, description: 'Capital U-acute' },
        { entityName: '&uacute;', entityNumber: 250, description: 'Lowercase U-acute' },
        { entityName: '&Ucirc;', entityNumber: 219, description: 'Capital U-circumflex' },
        { entityName: '&ucirc;', entityNumber: 251, description: 'Lowercase U-circumflex' },
        { entityName: '', entityNumber: 360, description: 'Capital U-tilde' },
        { entityName: '', entityNumber: 361, description: 'Lowercase U-tilde' },
        { entityName: '&Uuml;', entityNumber: 220, description: 'Capital U-umlaut' },
        { entityName: '&uuml;', entityNumber: 252, description: 'Lowercase U-umlaut' },
        { entityName: '', entityNumber: 366, description: 'Capital U-ring' },
        { entityName: '', entityNumber: 367, description: 'Lowercase U-ring' },
        { entityName: '', entityNumber: 362, description: 'Capital U-macron' },
        { entityName: '', entityNumber: 363, description: 'Lowercase U-macron' },
        { entityName: '', entityNumber: 364, description: 'Capital U-breve' },
        { entityName: '', entityNumber: 365, description: 'Lowercase U-breve' },
        { entityName: '', entityNumber: 370, description: 'Capital U-ogonek' },
        { entityName: '', entityNumber: 371, description: 'Lowercase U-ogonek' },
        { entityName: '', entityNumber: 368, description: 'Capital U-double acute' },
        { entityName: '', entityNumber: 369, description: 'Lowercase U-double acute' },
        { entityName: 'V', entityNumber: 86, description: 'Capital V' },
        { entityName: 'v', entityNumber: 118, description: 'Lowercase V' },
        { entityName: 'W', entityNumber: 87, description: 'Capital W' },
        { entityName: 'w', entityNumber: 119, description: 'Lowercase W' },
        { entityName: '', entityNumber: 7808, description: 'Capital W-grave' },
        { entityName: '', entityNumber: 7809, description: 'Lowercase W-grave' },
        { entityName: '', entityNumber: 7810, description: 'Capital W-acute' },
        { entityName: '', entityNumber: 7811, description: 'Lowercase W-acute' },
        { entityName: '', entityNumber: 372, description: 'Capital W-circumflex' },
        { entityName: '', entityNumber: 373, description: 'Lowercase W-circumflex' },
        { entityName: '', entityNumber: 7812, description: 'Capital W-umlaut' },
        { entityName: '', entityNumber: 7813, description: 'Lowercase W-umlaut' },
        { entityName: 'X', entityNumber: 88, description: 'Capital X' },
        { entityName: 'x', entityNumber: 120, description: 'Lowercase X' },
        { entityName: 'Y', entityNumber: 89, description: 'Capital Y' },
        { entityName: 'y', entityNumber: 121, description: 'Lowercase Y' },
        { entityName: '', entityNumber: 7922, description: 'Capital Y-grave' },
        { entityName: '', entityNumber: 7923, description: 'Lowercase Y-grave' },
        { entityName: '&Yacute;', entityNumber: 221, description: 'Capital Y-acute' },
        { entityName: '&yacute;', entityNumber: 253, description: 'Lowercase Y-acute' },
        { entityName: '', entityNumber: 374, description: 'Capital Y-circumflex' },
        { entityName: '', entityNumber: 375, description: 'Lowercase Y-circumflex' },
        { entityName: '&Yuml;', entityNumber: 159, description: 'Capital Y-umlaut' },
        { entityName: '&yuml;', entityNumber: 255, description: 'Lowercase Y-umlaut' },
        { entityName: 'Z', entityNumber: 90, description: 'Capital Z' },
        { entityName: 'z', entityNumber: 122, description: 'Lowercase Z' },
        { entityName: '', entityNumber: 377, description: 'Capital Z-acute' },
        { entityName: '', entityNumber: 378, description: 'Lowercase Z-acute' },
        { entityName: '', entityNumber: 381, description: 'Capital Z-hachek' },
        { entityName: '', entityNumber: 382, description: 'Lowercase Z-hachek' },
        { entityName: '', entityNumber: 379, description: 'Capital Z-dot' },
        { entityName: '', entityNumber: 380, description: 'Lowercase Z-dot' },
    ];
}

